# Generated by Django 5.0.7 on 2026-05-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approval_status(apps, schema_editor):
    DoctorProfile = apps.get_model("api", "DoctorProfile")
    DoctorProfile.objects.filter(is_approved=True).update(approval_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_approval_status, migrations.RunPython.noop),
    ]
