# Generated by Django 5.0.7 on 2026-05-13 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_hospitals(apps, schema_editor):
    Hospital = apps.get_model("api", "Hospital")
    Hospital.objects.filter(is_approved=False).update(is_approved=True, approval_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctorprofile_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_hospitals, migrations.RunPython.noop),
    ]
